# Generated by Django 3.0 on 2022-03-12 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_body', models.TextField(default='')),
                ('from_id', models.ForeignKey(db_column='from_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_chat_from', to=settings.AUTH_USER_MODEL)),
                ('to_id', models.ForeignKey(db_column='to_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_chat_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
