# Generated by Django 3.0 on 2022-03-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_auto_20220313_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
