# Generated by Django 3.0 on 2022-03-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_auto_20220313_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='time_stamp',
            field=models.DateTimeField(blank=True),
        ),
    ]
