# Generated by Django 3.0 on 2022-03-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_auto_20220314_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('time_stamp',)},
        ),
    ]
