# Generated by Django 3.0 on 2022-06-18 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='devoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('frontend_cnt', models.CharField(max_length=50)),
                ('backend_cnt', models.CharField(max_length=50)),
                ('android_cnt', models.CharField(max_length=50)),
                ('ios_cnt', models.CharField(max_length=50)),
                ('data_cnt', models.CharField(max_length=50)),
                ('devops_cnt', models.CharField(max_length=50)),
                ('body', models.TextField(default=0)),
                ('period', models.TextField(default=0)),
                ('done', models.CharField(max_length=50)),
                ('recruit_state', models.BooleanField(default=True)),
                ('date', models.CharField(max_length=50, null=True)),
                ('field', models.CharField(max_length=50, null=True)),
                ('writer', models.ForeignKey(db_column='user_name', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
