# Generated by Django 3.0 on 2022-06-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoard',
            name='belong',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
