# Generated by Django 3.0 on 2022-06-18 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devoard_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong', models.BooleanField(default=False, null=True)),
                ('awaiter', models.ManyToManyField(related_name='project_awaiter', to=settings.AUTH_USER_MODEL)),
                ('joiner', models.ManyToManyField(related_name='project_joiner', to=settings.AUTH_USER_MODEL)),
                ('project_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_detail', to='devoard_app.devoard')),
                ('team_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proejct_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
