# Generated by Django 3.0 on 2022-05-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220516_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='git_userImg',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_job',
            field=models.IntegerField(default=0),
        ),
    ]
