# Generated by Django 3.0 on 2022-05-13 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devoard_app', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='alter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('data', models.TextField(default='')),
                ('devoard_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devoard_data', to='devoard_app.devoard')),
                ('team_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_master', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
