# Generated by Django 3.0 on 2022-05-13 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '__first__'),
        ('alter_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alter',
            name='project_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_data', to='project_app.project'),
        ),
    ]
