# Generated by Django 3.2.9 on 2022-05-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alter_app', '0002_alter_project_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
